### ISSUE TITLE
Option to reuse ? Methods for deployment ?

### ISSUE THREAD

**Issue by fire17** [DenverCoder1/minimalistic-wallpaper-collection#86]
Hi @DenverCoder1 , 
was trying to fork and deploy this, but i guess this isnt jekyll or something that the github pages can natively run,
was wondering if you can share how can this be deployed?
I would have loved to just run it on github somehow, maybe vercel if not possible..
Would love to hear what you think
Really inspired by your work, Thanks a lot!

**Comment by fire17** [comment]
p.s - i'm trying to build a showcase page for my projects, this looks like the best thing that i've seen yet. super awesome

the idea is to have a nice looking page (like this wallpaper) but each one is a repository. It will fetch my/other's repos with github api, and be a really nice portal to a lot of cool data. I even imaging when clicking on it, instead of an image, you get a nicely formatted view of the project. this can show useful stats, graphs, etc - at the side, and mainly a scrollable section for the read me.

**Comment by fire17** [comment]
p.p.s - Do you think this wallpaper can be used inside of a README ? directly in a repo?
I'm not sure how it will be possible, but I see this is right up your alley, so i thought to ask 😄

**Comment by DenverCoder1** [comment]
It can't be run on GitHub Pages since it's not static (the HTML is generated by PHP).

It is currently hosted on Vercel and the necessary vercel.json and .vercelignore are included in the source code.

**Comment by DenverCoder1** [comment]
> Do you think this wallpaper can be used inside of a README ? directly in a repo?
I'm not sure how it will be possible, but I see this is right up your alley, so i thought i'd ask 😄

I've seen people do "wallpaper of the day" kind of things in their readme before, using my collection.

There's an API included for getting a random wallpaper each time (more info in the repo's readme).

For daily, etc, you can use a GitHub action such as update-image-readme. Example: https://github.com/GalexY727/GalexY727/blob/main/.github/workflows/daily-wallpaper.yml

**Comment by fire17** [comment]
> It can't be run on GitHub Pages since it's not static (the HTML is generated by PHP).
> 
> It is currently hosted on Vercel and the necessary vercel.json and .vercelignore are included in the source code.

Amazing Thank you

**Comment by fire17** [comment]
> > Do you think this wallpaper can be used inside of a README ? directly in a repo?
> > I'm not sure how it will be possible, but I see this is right up your alley, so i thought i'd ask 😄
> 
> I've seen people do "wallpaper of the day" kind of things in their readme before, using my collection.
> 
> There's an API included for getting a random wallpaper each time eg. using "https://minimalistic-wallpaper.demolab.com/?random" as the image source (more info in this repo's readme).
> 
> For daily, etc, you can use a GitHub action such as update-readme-image. Example: https://github.com/GalexY727/GalexY727/blob/main/.github/workflows/daily-wallpaper.yml

Thats cool i'll take a look at it,
but i was imagining not an image, but really each block having it's own link, and be directly in the readme
something like your readme-youtube 

lemme know if you catch my drift :)
Thanks a lot and have a good one!
oh and as a side bonus, (just because i love your work and their's) here's the best ChatGPT extension i've seen to date
[ChatGPT-History](https://chrome.google.com/webstore/detail/chatgpt-history/jjdnakkfjnnbbckhifcfchagnpofjffo/) - saves all your history, plus you can resume previous conversations, and other nice features - they really deserve many more stars on their [github repo](https://github.com/benf2004/ChatGPT-History)

**Comment by fire17** [comment]
> > Do you think this wallpaper can be used inside of a README ? directly in a repo?
> > I'm not sure how it will be possible, but I see this is right up your alley, so i thought i'd ask 😄
> 
> I've seen people do "wallpaper of the day" kind of things in their readme before, using my collection.
> 
> There's an API included for getting a random wallpaper each time eg. using "https://minimalistic-wallpaper.demolab.com/?random" as the image source (more info in this repo's readme).
> 
> For daily, etc, you can use a GitHub action such as update-readme-image. Example: https://github.com/GalexY727/GalexY727/blob/main/.github/workflows/daily-wallpaper.yml

Thats cool i'll take a look at it,
but i was imagining not an image, but really each block having it's own link, and be directly in the readme
something like your readme-youtube 

lemme know if you catch my drift :)
Thanks a lot and have a good one!
oh and as a side bonus, (just because i love your work and their's) here's the best ChatGPT extension i've seen to date
[ChatGPT-History](https://chrome.google.com/webstore/detail/chatgpt-history/jjdnakkfjnnbbckhifcfchagnpofjffo/) - saves all your history, plus you can resume previous conversations, and other nice features - they really deserve many more stars on their [github repo](https://github.com/benf2004/ChatGPT-History)
